name: Scan Image for vulnerabilities
description: Detect any known vulnerabilities in a pushed image

inputs:
  image_uri:
    required: true
    description: "URI of image to scan"
  critical_high_exit_code:
    required: true
    description: "Exit code for critical or high scanning, used to override"

runs:
  using: "composite"

  steps:
  #--Fail on detection of a Critical or High vuln
  - name: Trivy Scan (Critical and High)
    run: exit 0 # trivy-action step removed
  #--List all other vulns, but do not fail
  - name: Trivy Image Scan ()
    run: exit 0 # trivy-action step removed
