name: Scan Image for vulnerabilities
description: Detect any known vulnerabilities in a pushed image

inputs:
  image_uri:
    required: true
    description: "URI of image to scan"

runs:
  using: "composite"

  steps:
  #--Fail on detection of a Critical or High vuln
  - name: Trivy Scan (Critical and High)
    uses: aquasecurity/trivy-action@master
    with:
      image-ref: ${{ inputs.image_uri }}
      format: 'table'
      exit-code: '1'
      ignore-unfixed: false
      vuln-type: 'os,library'
      severity: 'CRITICAL,HIGH'

  #--List all other vulns, but do not fail
  - name: Trivy Image Scan ()
    uses: aquasecurity/trivy-action@master
    with:
      image-ref: ${{ inputs.image_uri }}
      format: 'table'
      exit-code: '0'
      ignore-unfixed: true
      vuln-type: 'os,library'
      severity: 'UNKNOWN,LOW,MEDIUM'
    env:
      TRIVY_SKIP_DB_UPDATE: true
      TRIVY_SKIP_JAVA_DB_UPDATE: true
