name: ecr-auth
description: Authenticate with AWS ECR

inputs:
  ecr_region:
    required: true
    description: "ECR Region"
  ecr_role:
    required: true
    description: "IAM Role to Assume for ECR"
  role-session-name:
    required: true
    description: "Unique Role Session Name"
  account_ids:
    required: false
    description: "List of AWS Account IDs for ECR Auth"

outputs:
  image_registry:
    description: "Image Registry URL"
    value: ${{ steps.login.outputs.registry }}

runs:
  using: "composite"

  steps:
  - name: AWS Auth
    id: auth
    uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
    with:
      role-to-assume: ${{ inputs.ecr_role }}
      aws-region: ${{ inputs.ecr_region }}
      role-session-name: ${{ inputs.role-session-name }}

  - name: ECR Login
    id: login
    uses: aws-actions/amazon-ecr-login@f2e9fc6c2b355c1890b65e6f6f0e2ac3e6e22f78 # v2.1.2
    with:
      registries: ${{ inputs.account_ids }}
