name: Resuable brakeman workflow

on: workflow_call

jobs:
  brakeman:
    name: scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #--v7.0.0
    - name: Set up ruby # this should inherit from your .ruby-version
      uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 #--v1.314.0
    - name: Setup Brakeman
      run: |
        gem install brakeman
    # Execute Brakeman CLI and generate a SARIF output with the security issues identified during the analysis
    - name: Scan
      continue-on-error: true
      run: |
        brakeman -f sarif -o output.sarif.json .
    # Upload the SARIF file generated in the previous step
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e #--v4.36.2
      with:
        sarif_file: output.sarif.json
