name: Resuable brakeman workflow

on: workflow_call

jobs:
  brakeman:
    name: scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #--v7.0.1
    - name: Set up ruby # this should inherit from your .ruby-version
      uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 #--v1.324.0
    - name: Setup Brakeman
      run: |
        gem install brakeman
    # Execute Brakeman CLI and generate a SARIF output with the security issues identified during the analysis
    - name: Scan
      continue-on-error: true
      run: |
        brakeman -f sarif -o output.sarif.json .
    # Upload the SARIF file generated in the previous step
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd #--v4.37.7
      with:
        sarif_file: output.sarif.json
