name: Build Image and Deploy to Cloud Platform

on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment Environment"
        required: false
        type: string
      dockerfile_path:
        description: "Path to build Dockerfile"
        required: true
        type: string
        default: Dockerfile #--Dockerfile in current working directory
      image_tag:
        description: "Image Tag"
        required: false
        type: string
        default: ${{ github.sha }}
      k8s_service_account:
        description: "Service Account for Kubernetes Authentication"
        required: false
        type: string
        default: cd-serviceaccount
      helm_release_name:
        description: "Release Name for helm install"
        required: true
        type: string
      helm_chart:
        description: "Helm chart to use for release"
        required: true
        type: string
      helm_values_path:
        description: "Path to values for helm deployment"
        required: true
        type: string
      helm_additional_args:
        description: "Any additional helm arguments"
        required: true
        type: string
    # secrets:
    #   ECR_REGION:
    #     description: "ECR Registry URL"
    #     required: true
    #   ECR_REGISTRY_URL:
    #     description: "ECR Registry URL"
    #     required: true
    #   KUBE_CLUSTER:
    #     description: "Kubernetes Cluster Name"
    #     required: true
    #   KUBE_NAMESPACE:
    #     description: "Kubernetes Namespace"
    #     required: true
    #   KUBE_TOKEN:
    #     description: "Kubernetes Authentication Token"
    #     required: true
    #   KUBE_CERT:
    #     description: "Kubernetes Cluster Certificate"
    #     required: true

jobs:
  build_and_push:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #--v4.2.2

      - name: ECR Auth
        id: auth
        uses: ./.github/actions/ecr-auth
        with:
          ecr_region: ${{ vars.ECR_REGION }}
          ecr_role: ${{ secrets.ECR_ROLE_TO_ASSUME }}

      - name: Build and Push
        id: build
        uses: ./.github/actions/build-and-push
        with:
          dockerfile_path: ${{ inputs.dockerfile_path }}
          image_registry: ${{ steps.auth.outputs.image_registry }}
          image_repo: ${{ vars.ECR_REPOSITORY }}
          image_tag: ${{ inputs.image_tag }}

      - name: Output
        id: output
        run: |
            echo image_registry=${{ steps.build.outputs.image_registry }} >> "$GITHUB_OUTPUT"
            echo image_repo=${{ steps.build.outputs.image_repo }} >> "$GITHUB_OUTPUT"
            echo image_tag=${{ steps.build.outputs.image_tag }} >> "$GITHUB_OUTPUT"
            echo image_uri="${{ steps.build.outputs.image_registry }}/${{ steps.build.outputs.image_repo }}:${{ steps.build.outputs.image_tag }}" >> "$GITHUB_OUTPUT"

    outputs:
      image_registry: ${{ steps.output.outputs.image_registry }}
      image_repo: ${{ steps.output.outputs.image_repo }}
      image_tag: ${{ steps.output.outputs.image_tag }}
      image_uri: ${{ steps.output.outputs.image_uri }}

  helm_deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: build_and_push
    environment: ${{ inputs.environment }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #--v4.2.2

      - name: Kube Authentication
        id: auth
        uses: ./.github/actions/authenticate_to_cluster
        with:
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace : ${{ secrets.KUBE_NAMESPACE }}
          kube-sa: ${{ inputs.k8s_service_account }}
          kube-token: "${{ secrets.KUBE_TOKEN }}"
          kube-cert: ${{ secrets.KUBE_CERT }}

      - name: Helm Deploy
        id: deploy
        uses: ./.github/actions/helm-deploy
        with:
          k8s_namespace: ${{ secrets.KUBE_NAMESPACE }}
          helm_release_name: ${{ inputs.helm_release_name }}
          helm_chart: ${{ inputs.helm_chart }}
          helm_values_path: ${{ inputs.helm_values_path }}
          helm_additional_args: ${{ inputs.helm_additional_args }}
          image_registry: ${{needs.build_and_push.outputs.image_registry}}
          image_repo: ${{needs.build_and_push.outputs.image_repo}}
          image_tag: ${{needs.build_and_push.outputs.image_tag}}
