#--Local workflow for this repo only. Not for remote consumption!

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  secret_detection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #--v7.0.0
        with:
          fetch-depth: 0

      - name: Secret Detection
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/secret-detection@0cb7eb8ab4bf643986ab36ecf3ffcdffa9b55214 # SHA for main as of 3 JUN 2026
