#--Local workflow for this repo only. Not for remote consumption!

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  secret_detection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #--v6.0.3
        with:
          fetch-depth: 0

      - name: Secret Detection
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/secret-detection@0cb7eb8ab4bf643986ab36ecf3ffcdffa9b55214 # SHA for main as of 3 JUN 2026
